version: 1.0.{build}
image: Visual Studio 2019
build_script:
  - pwsh: ./Microsoft/main.ps1
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))