version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:

  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  microsoft:
    executor: win/server-2022
    steps:
      - checkout
      - run:
          name: Install Selenium
          no_output_timeout: "10m"
          command: pwsh -Command "Install-Module Selenium -Repository PSGallery -Force"
      - run:
          name: Get some info
          no_output_timeout: "10m"
          command: pwsh -File ./Microsoft/main.ps1
          
workflows:
  # say-hello-workflow:
  #   jobs:
  #     - say-hello
  my-workflow:
    jobs:
      - microsoft
