name: CI Tests
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install tools
        run: |
          sudo apt-get -y update
          sudo apt-get install -y cabextract tree

  linux-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: selenium python
        run: tests/download.py
        shell: python

      - name: verify
        run: ./tests/download-check.ps1
        shell: pwsh