# This is a basic workflow to help you get started with Actions

name: Clear API Data
on:
  workflow_dispatch:

jobs:
  clear:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pre-reqs
        run: sudo apt-get -y update; sudo apt-get -y install tree
      - name: Clear API
        run: ./tasks/clear-api.ps1
        shell: pwsh

