# This is a basic workflow to help you get started with Actions

name: Clear API Data
on:
  workflow_dispatch:

jobs:
  clear:
    runs-on: ubuntu-latest
    steps:
      - name: Clear API
        shell: pwsh
        run: Get-ChildItem -Path . -Recurse -Filter "clear-api.ps1" | iex $_.FullName

