name: Selenium Tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi

      - name: Generate Dell CSV Data
        run: |
          mFiles=`find ./src/Dell -name "*.py"`
          for f in "${mFiles}[@]}"
          do
            python3 "$f"
          done
        shell: sh