name: Main Task

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi

      # - name: Generate Dell CSV Data
      #   run: |
      #     mFiles=`find src/Dell -name "*.py"`
      #     for f in ${mFiles[@]}
      #     do
      #       python3 "$f"
      #     done
      #   shell: bash

      - name: Generate HP CSV Data
        run: |
          mFiles=`find src/HP -name "*.py"`
          for f in ${mFiles[@]}
          do
            python3 "$f"
          done
        shell: bash
      
      # - name: Generate Lenovo CSV Data
      #   run: |
      #     mFiles=`find src/Lenovo -name "*.py"`
      #     for f in ${mFiles[@]}
      #     do
      #       python3 "$f"
      #     done
      #   shell: bash

      # - name: Archive Dell CSV output
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Dell
      #     path: |
      #       src/Dell/Latitude/output
      #       src/Dell/OptiPlex/output
      #       src/Dell/XPS/output
      #     retention-days: 3

      - name: Archive HP CSV output
        uses: actions/upload-artifact@v3
        with:
          name: HP
          path: src/HP/output
          retention-days: 3

      # - name: Archive Lenovo CSV output
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Lenovo
      #     path: |
      #       src/Lenovo/LenovoLaptop/output
      #       src/Lenovo/ThinkCentre/output
      #       src/Lenovo/ThinkPad/output
      #       src/Lenovo/ThinkStation/output
      #     retention-days: 3

      # - name: Inject Dell
      #   run: |
      #     . ./app/load-functions.ps1
      #     . ./app/Dell/dell-latitude.ps1
      #     . ./app/Dell/dell-optiplex.ps1
      #     . ./app/Dell/dell-xps.ps1
      #   shell: pwsh