name: Selenium Tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi

      - name: Generate Dell CSV Data
        run: |
          mFiles=`find src/Dell -name "*.py"`
          for f in ${mFiles[@]}
          do
            python3 "$f"
          done
        shell: bash

      - name: Generate HP CSV Data
        run: |
          mFiles=`find src/HP -name "*.py"`
          for f in ${mFiles[@]}
          do
            python3 "$f"
          done
        shell: bash
      
      - name: Generate Lenovo CSV Data
        run: |
          mFiles=`find src/Lenovo -name "*.py"`
          for f in ${mFiles[@]}
          do
            python3 "$f"
          done
          tree
        shell: bash

      # - name: Archive Dell CSV output
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Dell
      #     path: /home/runner/work/optechx.drivers/optechx.drivers/bs4/Dell
      #     retention-days: 3

      # - name: Archive HP CSV output
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: HP
      #     path: /home/runner/work/optechx.drivers/optechx.drivers/bs4/HP
      #     retention-days: 3

      # - name: Archive Lenovo CSV output
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Lenovo
      #     path: /home/runner/work/optechx.drivers/optechx.drivers/bs4/Lenovo
      #     retention-days: 3