name: Selenium Tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi

      - name: Generate Dell CSV Data
        run: |
          python3 src/Dell/OptiPlex/win11-dell-optiplex.py
          python3 src/Dell/OptiPlex/win10-dell-optiplex.py
          python3 src/Dell/XPS/win10-dell-xps.py
          python3 src/Dell/XPS/win11-dell-xps.py
          python3 src/Dell/Latitude/win10-dell-latitude.py
          python3 src/Dell/Latitude/win11-dell-latitude.py
        shell: sh

      - name: Generate HP CSV Data
        run: python3 src/HP/main-hp.py
        shell: sh
      
      - name: Generate Lenovo CSV Data
        run: |
          mFiles=`find src/Lenovo -name "*.py"`
          for f in "${mFiles[@]}"
          do
            echo "$f"
          done
        shell: bash